### ISSUE TITLE
Subtlety 

### ISSUE THREAD

**Issue by davecastlevania** [CA-lancem/prj-rev-bwfs-dasmoto#1]
https://github.com/CA-lancem/prj-rev-bwfs-dasmoto/blob/master/DasmotoAC/index.html#L6
https://github.com/CA-lancem/prj-rev-bwfs-dasmoto/blob/master/DasmotoAC/index.html#L10

Use this for ampersands 

`&amp;`

**Comment by CA-lancem** [comment]
Thank you for pointing this out. I will try to remember to use this going forward.

This is my first time using Issues in GitHub, what is the recommended workflow for closing this issue? Am I expected to close all issues associated with my project submissions?

**Comment by CA-lancem** [comment]
Re-opening; missed the semi-colon in previous commit.
